"use client";
import dynamic from "next/dynamic";
import Image from "next/image";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";import {ScrollTrigger} from "gsap/ScrollTrigger";import Lenis from "lenis";
import {ArrowDownRight,ArrowUpRight,Menu,Play,Sparkles,X} from "lucide-react";import {Button} from "@/components/ui/button";
const OrbScene=dynamic(()=>import("@/components/orb-scene").then(m=>m.OrbScene),{ssr:false});
const worlds=[
 {title:"NEON DIVIDE",tag:"CYBER ARENA",image:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=85"},
 {title:"LOST SIGNAL",tag:"OPEN WORLD",image:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1600&q=85"},
 {title:"WILD CIRCUIT",tag:"RACING",image:"https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=85"}];
const posts=["THE MINDS THAT CHANGED THE GAME","HOW AI BUILDS WORLDS IN SECONDS","INSIDE THE FUTURE OF PLAY"];
export function BerryBoxExperience(){const root=useRef<HTMLDivElement>(null);const[menu,setMenu]=useState(false);const[loaded,setLoaded]=useState(false);
useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;const lenis=new Lenis({duration:.9,smoothWheel:true,syncTouch:true,syncTouchLerp:.075,touchInertiaExponent:1.7,touchMultiplier:1.05,anchors:true});let frame=0;const raf=(t:number)=>{lenis.raf(t);frame=requestAnimationFrame(raf)};if(!reduce)frame=requestAnimationFrame(raf);const timer=setTimeout(()=>setLoaded(true),reduce?50:1700);const ctx=gsap.context(()=>{if(reduce)return;gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach(el=>gsap.fromTo(el,{y:70,opacity:0},{y:0,opacity:1,duration:1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 88%"}}));gsap.utils.toArray<HTMLElement>("[data-parallax]").forEach(el=>gsap.to(el,{yPercent:-12,ease:"none",scrollTrigger:{trigger:el.parentElement,start:"top bottom",end:"bottom top",scrub:.8}}));gsap.to(".hero-a",{xPercent:-8,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}});gsap.to(".hero-b",{xPercent:8,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}});gsap.fromTo(".hero-card",{opacity:0,scale:.78,y:80,rotate:-7},{opacity:1,scale:1,y:0,rotate:0,duration:1.35,stagger:.16,ease:"expo.out",delay:.25});gsap.to(".hero-card-one",{y:-24,rotate:2,duration:3.2,repeat:-1,yoyo:true,ease:"sine.inOut"});gsap.to(".hero-card-two",{y:20,rotate:-3,duration:3.8,repeat:-1,yoyo:true,ease:"sine.inOut"});gsap.to(".hero-card-three",{y:-16,x:10,rotate:2,duration:4.1,repeat:-1,yoyo:true,ease:"sine.inOut"})},root);return()=>{clearTimeout(timer);cancelAnimationFrame(frame);lenis.destroy();ctx.revert()}},[]);
return <div ref={root} className="site"><div className={`loader ${loaded?"done":""}`} aria-hidden={loaded}><Image className="loader-logo" src="/berrybox.png" alt="" width={420} height={180} priority/><div><i/></div><p>BUILDING YOUR NEXT WORLD</p></div>
<header><a className="logo" href="#top" aria-label="Berrybox home"><Image src="/berrybox.png" alt="Berrybox" width={220} height={82} priority/></a><nav><a href="#worlds">WORLDS</a><a href="#why">WHY US</a><a href="#stories">STORIES</a></nav><a className="cta desktop button-link" href="#join">GET STARTED <ArrowUpRight/></a><button className="mobile" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button></header>
<div className={`mobile-nav ${menu?"open":""}`}><button aria-label="Close menu" onClick={()=>setMenu(false)}><X/></button>{[["WORLDS","worlds"],["WHY US","why"],["STORIES","stories"]].map(([n,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{n}</a>)}</div>
<main id="top"><section className="hero"><div className="orb"><OrbScene/></div><div className="grid"/><div className="hero-gallery" aria-hidden="true"><div className="hero-card hero-card-one"/><div className="hero-card hero-card-two"/><div className="hero-card hero-card-three"/></div><div className="kicker"><span>AI GAME CREATION PLATFORM</span><span>CREATE / CUSTOMIZE / PUBLISH / PLAY</span></div><div className="hero-content"><p className="eyebrow lime">BUILD WHAT&apos;S NEXT</p><h1><span className="hero-a">CREATE GAMES</span><span className="hero-b">WITH AI.</span></h1><div className="hero-bottom"><p>TURN A PROMPT INTO A PLAYABLE UNIVERSE. NO CODE, NO LIMITS — JUST YOUR IMAGINATION IN MOTION.</p><div><a className="cta button-link" href="#worlds">START CREATING <ArrowDownRight/></a><Button variant="outline" className="ghost"><Play/> WATCH DEMO</Button></div></div></div></section>
<section id="why" className="why"><p data-reveal className="eyebrow">01 — WHY BERRYBOX</p><h2 data-reveal>THE FUTURE ISN&apos;T PLAYED. <span>IT&apos;S CREATED.</span></h2><div className="why-grid"><p data-reveal>TRADITIONAL GAME CREATION NEEDS CODE, ENGINES AND MASSIVE TEAMS. BERRYBOX TURNS IDEAS INTO INTERACTIVE EXPERIENCES WITH A SENTENCE.</p><div className="features">{[["01","VR READY"],["02","LIVE WORLDS"],["03","MULTIPLAYER"],["04","ONE-CLICK PLAY"]].map(([n,l])=><article data-reveal key={n}><small>{n}</small><Sparkles/><h3>{l}</h3></article>)}</div></div></section>
<section id="worlds" className="worlds"><div className="marquee"><div>AI-POWERED WORLDS ? EVERY ADVENTURE ? NO CODE REQUIRED ? AI-POWERED WORLDS ? EVERY ADVENTURE ? NO CODE REQUIRED ?</div></div><div className="section-pad"><p data-reveal className="eyebrow lime">02 — FEATURED GAME WORLDS</p><h2 data-reveal>ENTER THE <span>UNKNOWN.</span></h2><div className="cards">{worlds.map((w,i)=><article data-reveal className="world-card" key={w.title}><div data-parallax className="world-image" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.88),rgba(0,0,0,.08)),url('${w.image}')`}}/><div className="world-copy"><div><span>0{i+1}</span><span>{w.tag}</span></div><div><h3>{w.title}</h3><button>EXPLORE WORLD <ArrowUpRight/></button></div></div></article>)}</div></div></section>
<section className="gameplay"><div className="shade"/><div className="game-copy"><p data-reveal className="eyebrow lime">03 — LOVE TO PLAY</p><h2 data-reveal>SWEET<br/><span>REVENGE</span></h2><p data-reveal>A FEVER-DREAM COMBAT WORLD SHAPED BY EVERY CHOICE. CREATE THE MISSION, INVITE THE SQUAD, REWRITE THE ENDING.</p></div><button className="play" aria-label="Play game trailer"><Play fill="currentColor"/></button></section>
<section id="stories" className="stories"><p data-reveal className="eyebrow lime">04 — PLAYER STORIES</p><h2 data-reveal>IMAGINATION IS THE ONLY <span>CONTROLLER.</span></h2><blockquote data-reveal><div><i/><b>MARCUS J.</b><small>CREATOR / PLAYER</small></div><p>“I DESCRIBED A WORLD I&apos;D BEEN DREAMING ABOUT FOR YEARS. MINUTES LATER, MY FRIENDS AND I WERE RUNNING THROUGH IT.”</p></blockquote></section>
<section className="news"><div className="news-head"><div><p className="eyebrow">05 — LATEST NEWS</p><h2>FIELD NOTES.</h2></div><ArrowUpRight/></div><div className="post-grid">{posts.map((p,i)=><article data-reveal key={p}><small>11 JUL 2026 / 0{i+1}</small><div style={{backgroundImage:`url('https://images.unsplash.com/photo-${["1550745165-9bc0b252726f","1542751110-97427bbecf20","1552820728-8b83bb6b773f"][i]}?auto=format&fit=crop&w=900&q=80')`}}/><h3>{p}</h3><ArrowUpRight/></article>)}</div></section></main>
<footer id="join"><p className="eyebrow">YOUR WORLD IS WAITING</p><h2 data-reveal>MAKE THE GAME <span>ONLY YOU</span> CAN IMAGINE.</h2><div className="signup"><p>GET PRODUCT DROPS, CREATOR STORIES AND NEW WORLD RELEASES IN YOUR INBOX.</p><form onSubmit={e=>e.preventDefault()}><input aria-label="Email address" placeholder="YOUR EMAIL ADDRESS" type="email"/><button aria-label="Subscribe"><ArrowUpRight/></button></form></div><div className="foot-grid"><div><Image className="footer-logo" src="/berrybox.png" alt="Berrybox" width={260} height={100}/><p>AI-POWERED GAME WORLDS FOR THE NEXT GENERATION OF CREATORS.</p></div><p><b>EXPLORE</b><br/>WORLDS<br/>CREATORS<br/>ABOUT</p><p><b>FOLLOW</b><br/>DISCORD<br/>YOUTUBE<br/>INSTAGRAM</p></div><div className="copyright"><span>© 2026 BERRYBOX</span><span>BUILT FOR THE BOLD</span></div></footer><div className="cursor-ring" aria-hidden="true"/><div className="cursor-dot" aria-hidden="true"/></div>}





